---
version: "2.0"
services:
  aorta_sarosiak:
    image: s4ros/aorta:latest
    restart: always
    container_name: aorta_sarosiak
    environment:
        - aorta_channel=sarosiak
        - aorta_database=sarosiak.db
        - aorta_adv=False
        - aorta_currency=hajsy
    volumes:
      - ./:/python
