# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('popularity', models.IntegerField(default=0)),
                ('money', models.IntegerField(default=0)),
                ('last_seen', models.DateField(default=django.utils.timezone.now)),
                ('time_spent', models.IntegerField(default=0)),
                ('is_following', models.BooleanField(default=False)),
                ('is_subscribing', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('text', models.CharField(max_length=350)),
                ('nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatter', to='aorta.Chatter')),
            ],
        ),
    ]
